In [21]:
from sklearn.metrics import DistanceMetric
import pandas as pd
import numpy as np

dist = DistanceMetric.get_metric('jaccard')
df = pd.read_csv("./CLI_examples/SMILES_repre.csv")
df = df.drop(['Label','Structure'],axis = 1)
arr = np.array(df)
print(arr)
mat = dist.pairwise(arr)
print(mat)

[[ 0.77627915  1.4811609  -0.05216069 ... -0.30313802 -0.9140043
  -1.5830982 ]
 [ 0.1759468   1.8608587  -0.37749845 ... -0.1339534  -1.2643373
  -1.4244325 ]
 [ 1.0030795   0.35911945 -0.04766299 ... -0.5599432  -0.14949572
  -1.2449317 ]
 ...
 [ 1.5002239  -0.78065115  0.6538213  ...  0.16849265 -0.80160636
  -0.75527793]
 [ 0.3644195  -0.28653458  1.0267187  ...  1.3895043   0.08948372
   0.6234026 ]
 [ 1.848001   -1.7906517   0.21971849 ... -0.22112082  0.5636611
  -0.3599808 ]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
